env:
  test2
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 65261599Duck
    url: jdbc:mysql://localhost:3306/wechatOrderSystem?characterEncoding=utf-8&useSSL=false
    username: root
