spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 65261599Duck
    url: jdbc:mysql://localhost:3306/wechatOrderSystem?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
