spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 65261599Duck
    url: jdbc:mysql://localhost:3306/wechatOrderSystem?characterEncoding=utf-8&useSSL=false
    username: root
  redis:
    host: 127.0.0.1
    port: 6379
    
